/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PRESENTACION;

import DATOS.Consultas_ingreso;
import DATOS.MetodosBD;
import LOGICA.RESULT_LOG;
import LOGICA.RESULT_TRAMITE;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.LinkedList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;


/**
 *
 * @author USUARIO
 */
public class INGRESO_DOCUMENTOS extends javax.swing.JInternalFrame {

    
    Consultas_ingreso doc_ing;
    
    
    public INGRESO_DOCUMENTOS() {
        initComponents();
       
//*******************************************************        
       Calendar cal= Calendar.getInstance();
       int year= cal.get(Calendar.YEAR);
       lbl_año_REG.setText(""+year);
       lbl_año_EXP.setText(""+year);
//*******************************************************
       Date myDate = new Date();
//       txt_f_ingreso.setText(""+new SimpleDateFormat("dd/MM/yy").format(myDate));
       
       pnl_oposicion.setVisible(false);
       doc_ing= new Consultas_ingreso();
       txt_reg.setText(String.valueOf(doc_ing.Ultimo_Id_tramite()+1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_reg = new javax.swing.JTextField();
        lbl_nro_catastro = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_exp = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btn_guardar = new javax.swing.JButton();
        lbl_año_REG = new javax.swing.JLabel();
        lbl_año_EXP = new javax.swing.JLabel();
        lbl_nro_catastro1 = new javax.swing.JLabel();
        pnl_oposicion = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_opo_reg = new javax.swing.JTextField();
        txt_opo_direcc = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_opo_nombre = new javax.swing.JTextField();
        chk_oposicion = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_nro_folios = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_monto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cb_categoria = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cb_doc_ingreso = new javax.swing.JComboBox<>();
        txt_detalle_documentoing = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_asunto = new javax.swing.JTextField();
        txt_f_ingreso = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_apellido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_direccion = new javax.swing.JTextField();
        chk_adjuntar = new javax.swing.JCheckBox();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(0, 51, 102));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INGRESO DE DOCUMENTOS");
        jLabel1.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("NRO. DE REGISTRO CATASTRO");

        txt_reg.setBackground(new java.awt.Color(204, 204, 255));

        lbl_nro_catastro.setText("-");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("EXP / MP");

        btn_guardar.setText("GUARDAR");
        btn_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_guardarMouseClicked(evt);
            }
        });
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });

        lbl_año_REG.setText("2020");

        lbl_año_EXP.setText("2020");

        lbl_nro_catastro1.setText("-");

        pnl_oposicion.setBackground(new java.awt.Color(255, 255, 204));
        pnl_oposicion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Oposiciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 255))); // NOI18N

        jLabel9.setText("NRO REG");

        jLabel10.setText("DIRECCION");

        jLabel15.setText("NOMBRE PROPIETARIO");

        javax.swing.GroupLayout pnl_oposicionLayout = new javax.swing.GroupLayout(pnl_oposicion);
        pnl_oposicion.setLayout(pnl_oposicionLayout);
        pnl_oposicionLayout.setHorizontalGroup(
            pnl_oposicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_oposicionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_oposicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_oposicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_opo_reg)
                    .addComponent(txt_opo_direcc, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_opo_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        pnl_oposicionLayout.setVerticalGroup(
            pnl_oposicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_oposicionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_oposicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_opo_reg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txt_opo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl_oposicionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_opo_direcc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        chk_oposicion.setBackground(new java.awt.Color(255, 255, 255));
        chk_oposicion.setText("Añadir oposición");
        chk_oposicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_oposicionActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de documento", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 255))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("NRO DE FOLIOS");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel11.setText("FECHA DE INGRESO");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 51, 153));
        jLabel12.setText("MONTO");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 153));
        jLabel13.setText("CATEGORIA");

        cb_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Licencias", "Sanemiento", "Otro" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("DOCUMENTO DE INGRESO");

        cb_doc_ingreso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carta ", "FUT", "Informe N°", "Memorando", "Memorial", "Oficio N°", "Solicitud", "Otro" }));

        txt_detalle_documentoing.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_detalle_documentoingFocusLost(evt);
            }
        });
        txt_detalle_documentoing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txt_detalle_documentoingMouseEntered(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel14.setText("ASUNTO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_nro_folios))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_doc_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_detalle_documentoing, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_f_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_asunto, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(txt_monto, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cb_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txt_nro_folios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12)
                        .addComponent(txt_monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addComponent(cb_categoria, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_f_ingreso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cb_doc_ingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_detalle_documentoing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txt_asunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de administrado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(153, 153, 255))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("NOMBRES");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setText("APELLIDOS");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setText("DIRECCIÓN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_apellido))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_direccion)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        chk_adjuntar.setBackground(new java.awt.Color(255, 153, 153));
        chk_adjuntar.setText("Adjuntar al expediente");
        chk_adjuntar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_adjuntarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_nro_catastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_año_REG, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_exp, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_nro_catastro1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_año_EXP, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(chk_adjuntar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chk_oposicion)
                        .addGap(879, 879, 879))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(921, 921, 921)
                                .addComponent(btn_guardar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pnl_oposicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator1)
                .addGap(123, 123, 123))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_reg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nro_catastro)
                    .addComponent(jLabel4)
                    .addComponent(txt_exp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_año_REG)
                    .addComponent(lbl_nro_catastro1)
                    .addComponent(lbl_año_EXP)
                    .addComponent(chk_adjuntar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chk_oposicion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl_oposicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1031, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_guardarMouseClicked
        // TODO add your handling code here:

        

    }//GEN-LAST:event_btn_guardarMouseClicked

    private void chk_oposicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_oposicionActionPerformed
        
        if (chk_oposicion.isSelected()){
            pnl_oposicion.setVisible(true);
        }else {
            pnl_oposicion.setVisible(false);
        }
        
    }//GEN-LAST:event_chk_oposicionActionPerformed
MetodosBD metodosbd=new MetodosBD();
    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        int id=0;
        validar_campos();
        if (JOptionPane.showConfirmDialog(rootPane, "¿Desea guardar la información?","Confirmación de guardado",JOptionPane.WARNING_MESSAGE,
            JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            
            id= doc_ing.Ultimo_Id_tramite()+1;
            String fecha= Date_a_String(txt_f_ingreso.getDate());
            String fecha_venc = Date_a_String(sumarDiasFecha(txt_f_ingreso.getDate(),3));
            
            
            doc_ing.Guardar_administrado(id,txt_nombre.getText(), txt_apellido.getText(), txt_direccion.getText());
            doc_ing.Guardar_monto(id,cb_categoria.getSelectedItem().toString(), Double.parseDouble(txt_monto.getText()));
            doc_ing.Guardar_doc_ingreso(id, Integer.parseInt(txt_nro_folios.getText()), fecha, (String)cb_doc_ingreso.getSelectedItem() ,txt_detalle_documentoing.getText() , txt_asunto.getText());
            doc_ing.Guardar_plazo(id, fecha, fecha_venc);
            doc_ing.Guardar_tramite(id, Integer.parseInt(txt_exp.getText()), Integer.parseInt(lbl_año_REG.getText()));
            metodosbd.guardar_proveido("sin proveido",txt_reg.getText());
            Limpiar_campos();
            txt_reg.setText(String.valueOf(doc_ing.Ultimo_Id_tramite()+1));
            
        }
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void txt_detalle_documentoingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_detalle_documentoingMouseEntered
     
        txt_detalle_documentoing.setToolTipText("Ingrese DETALLE de documento");
       
    }//GEN-LAST:event_txt_detalle_documentoingMouseEntered

    private void txt_detalle_documentoingFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_detalle_documentoingFocusLost
        txt_asunto.setText(txt_detalle_documentoing.getText());
    }//GEN-LAST:event_txt_detalle_documentoingFocusLost

    private void chk_adjuntarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_adjuntarActionPerformed
        
        if (chk_adjuntar.isSelected() && txt_reg.getText().isEmpty()==false){
           txt_exp.setBackground(Color.YELLOW);
           txt_reg.setBackground(Color.YELLOW);
           txt_nro_folios.setBackground(Color.YELLOW);
           txt_f_ingreso.setBackground(Color.YELLOW);
           btn_guardar.setText("Adjuntar");
           
           LinkedList<RESULT_TRAMITE> Listado = new LinkedList<RESULT_TRAMITE>();
           Listado = doc_ing.Listar_tramite_existente(Integer.parseInt(txt_reg.getText()));
            System.out.println(Listado.element().toString());
           cb_categoria.setSelectedItem(Listado.element().getTipo_monto());
           txt_monto.setText(String.valueOf(Listado.element().getCantidad()));
           cb_doc_ingreso.setSelectedItem(Listado.element().getTipo_doc_ing());
           txt_detalle_documentoing.setText(Listado.element().getDetalle());
           txt_asunto.setText(Listado.element().getAsunto());
           txt_nombre.setText(Listado.element().getNombre());
           txt_apellido.setText(Listado.element().getApellido());
           txt_direccion.setText(Listado.element().getDireccion());
//          
        }else{
           if (chk_adjuntar.isSelected() && txt_reg.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(rootPane, "Debe llenar el campo Nro de REG ");
                    chk_adjuntar.setSelected(false);
           } else {
                txt_exp.setBackground(Color.WHITE);
                Color color= new Color(204,204,255);
                txt_reg.setBackground(color);
                txt_nro_folios.setBackground(Color.WHITE);
                txt_f_ingreso.setBackground(Color.WHITE);
                btn_guardar.setText("Guardar");
                Limpiar_campos();
                txt_reg.setText(String.valueOf(doc_ing.Ultimo_Id_tramite()+1));
                
           }
          
        }
    }//GEN-LAST:event_chk_adjuntarActionPerformed

  	private void Limpiar_campos(){
            txt_apellido.setText("");
            txt_asunto.setText("");
            txt_detalle_documentoing.setText("");
            txt_direccion.setText("");
            txt_exp.setText("");
            txt_f_ingreso.cleanup();
            txt_monto.setText("");
            txt_nro_folios.setText("");
            txt_nombre.setText("");
            txt_opo_direcc.setText("");
            txt_opo_nombre.setText("");
            txt_opo_reg.setText("");
            txt_reg.setText("");
            
        }
 public Date sumarDiasFecha(Date fecha, int dias){

      Calendar calendar = Calendar.getInstance();
	
      calendar.setTime(fecha); // Configuramos la fecha que se recibe
	
      calendar.add(Calendar.DAY_OF_YEAR, dias);  // numero de días a añadir, o restar en caso de días<0

      return calendar.getTime(); // Devuelve el objeto Date con los nuevos días añadidos
	
 }
    
    private String Date_a_String(Date fecha){
        Calendar c = Calendar.getInstance();
        c.setTime(fecha);

        String dia = Integer.toString(c.get(Calendar.DATE));
        String mes = Integer.toString((c.get(Calendar.MONTH))+1);
        String annio = Integer.toString(c.get(Calendar.YEAR));
        return annio+"-"+(mes)+"-"+dia;     
}
    
    private  boolean isNumeric(String cadena){
	try {
		Integer.parseInt(cadena);
		return true;
	} catch (NumberFormatException nfe){
		return false;
	}
    }
    
    private boolean validar_campos (){
        
            if (txt_reg.getText().equals("") ) {
                JOptionPane.showMessageDialog(null, "Debe llenar el campo NRO. DE REGISTRO CATASTRO para continuar");
                return false;
            }
            
            if (!isNumeric(txt_reg.getText()) ) {
                JOptionPane.showMessageDialog(null, "Debe llenar datos válidos en el campo NRO. DE REGISTRO CATASTRO para continuar");
                return false;
            }
            
            if (txt_exp.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Debe llenar el campo EXP/MP para continuar");
                return false;
            }
            if (!isNumeric(txt_exp.getText()) ) {
                JOptionPane.showMessageDialog(null, "Debe llenar datos válidos en el campo EXP/MP para continuar");
                return false;
            }
            if (txt_nro_folios.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Debe llenar el campo NRO FOLIOS para continuar");
                return false;
            }
            
            if (!isNumeric(txt_nro_folios.getText()) ) {
                JOptionPane.showMessageDialog(null, "Debe llenar datos válidos en el campo NRO FOLIOS para continuar");
                return false;}
            
            if (txt_f_ingreso.getDate().toString().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Debe llenar el campo FECHA DE INGRESO para continuar");
                return false;
            }
            if (txt_detalle_documentoing.getText().equals("")) {
                JOptionPane.showMessageDialog(null,"Debe llenar el campo DOCUMENTO DE INGRESO para continuar");
                return false;
            }
            if (txt_nombre.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Debe llenar el campo NOMBRE para continuar");
                return false;
            }
            
            if (txt_apellido.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Debe llenar el campo APELLIDO para continuar");
                return false;
            }
            
            if (txt_direccion.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Debe llenar el campo DIRECCION para continuar");
                return false;
            }
            
            if (pnl_oposicion.isVisible()) {
                if (txt_opo_direcc.getText().equals("") && txt_opo_nombre.getText().equals("")&& txt_opo_reg.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Debe llenar alguno de los campos de OPOCISIÓN para continuar");
                    return false;
                    
                }
            }
            
        
            return true;
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cb_categoria;
    private javax.swing.JComboBox<String> cb_doc_ingreso;
    private javax.swing.JCheckBox chk_adjuntar;
    private javax.swing.JCheckBox chk_oposicion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_año_EXP;
    private javax.swing.JLabel lbl_año_REG;
    private javax.swing.JLabel lbl_nro_catastro;
    private javax.swing.JLabel lbl_nro_catastro1;
    private javax.swing.JPanel pnl_oposicion;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_asunto;
    private javax.swing.JTextField txt_detalle_documentoing;
    private javax.swing.JTextField txt_direccion;
    private javax.swing.JTextField txt_exp;
    private com.toedter.calendar.JDateChooser txt_f_ingreso;
    private javax.swing.JTextField txt_monto;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nro_folios;
    private javax.swing.JTextField txt_opo_direcc;
    private javax.swing.JTextField txt_opo_nombre;
    private javax.swing.JTextField txt_opo_reg;
    private javax.swing.JTextField txt_reg;
    // End of variables declaration//GEN-END:variables
}
